services:
  postgres:
    image: postgres:15
    container_name: horizon-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - horizon-pgdata:/var/lib/postgresql/data
    networks:
      - horizon-net 
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrator:
    image: migrate/migrate
    container_name: horizon-migrator
    networks:
      - horizon-net
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./db/migrations:/migrations
    entrypoint: ["migrate"]
    command: [
      "-path", "/migrations",
      "-database", "postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?sslmode=disable",
      "up"
    ]
    environment:
      MIGRATIONS_PATH: /migrations

volumes: 
  horizon-pgdata:

networks:
  horizon-net: