// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: health.sql

package db

import (
	"context"
)

const checkDBConnection = `-- name: CheckDBConnection :one
SELECT NOW() AS db_time
`

func (q *Queries) CheckDBConnection(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRow(ctx, checkDBConnection)
	var db_time interface{}
	err := row.Scan(&db_time)
	return db_time, err
}
